// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbdvxffykgbhrdcveuzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZHZ4ZmZ5a2diaHJkY3ZldXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjY0ODksImV4cCI6MjA2NDQ0MjQ4OX0.ozJEGEPX8fXj6eOsffzDpPO6DsIx66bTXj0C4z-zHCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);